add_item:
  fields:
    name:
      example: Restje lasagne
      selector:
        text:
    contents:
      example: lasagne met gehakt
      selector:
        text:
    location:
      selector:
        select:
          options:
            - koelkast
            - vriezer
            - buiten
          translation_key: item_location
    added_date:
      selector:
        text:
    expiry_date:
      selector:
        text:
    quantity:
      example: 2 bakjes
      selector:
        text:

update_item:
  fields:
    id:
      required: true
      selector:
        text:

remove_item:
  fields:
    id:
      required: true
      selector:
        text:

complete_item:
  fields:
    id:
      required: true
      selector:
        text:
    action:
      required: true
      selector:
        select:
          options:
            - eaten
            - tossed
          translation_key: complete_action

remove_expired:

estimate:
  fields:
    name:
      required: true
      example: krop sla
      selector:
        text:

add_template:
  fields:
    name:
      required: true
      selector:
        text:

print_sticker:
  fields:
    id:
      required: true
      selector:
        text:

run_check:
